version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 10
      runas: root
