version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/deploy
hooks:
  AfterInstall:
    - location: scripts/load_image.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
